tasks:
  - before: |
      sudo apt update -y
      DEBIAN_FRONTEND=noninteractive sudo apt-get install -y bison python3-dev libcppunit-dev build-essential cmake autoconf tcl pkg-config git curl patch libtool-bin

    init: |
      make NPROC=16 # gitpod.io offers 16 CPU & 60 GB RAM
      make install

vscode:
  extensions:
    - ms-vscode.cpptools-extension-pack
