tasks:
  - before: |
      sudo apt update -y
      DEBIAN_FRONTEND=noninteractive sudo apt-get install -y bison python3-dev libcppunit-dev build-essential cmake autoconf tcl pkg-config git curl patch libtool-bin

      # install bazel
      sudo apt install -y apt-transport-https curl gnupg
      curl -fsSL https://bazel.build/bazel-release.pub.gpg | gpg --dearmor > bazel.gpg
      sudo mv bazel.gpg /etc/apt/trusted.gpg.d/
      echo "deb [arch=amd64] https://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
      sudo apt update -y && sudo apt install -y bazel
      sudo ln -s /usr/bin/bazel /usr/bin/bazel-1.0.0

    init: |
      make NPROC=16 # gitpod.io offers 16 CPU & 60 GB RAM
      make install

vscode:
  extensions:
    - ms-vscode.cpptools-extension-pack
