apiVersion: v1
kind: Service
metadata:
  name: openmldb-kafka-connect-service
spec:
  selector:
    app: openmldb-kafka-connect
  ports:
  - name: kafka-connect
    port: 8083
    targetPort: 8083
    nodePort: 8083
  type: NodePort
