# Copyright 2021 4Paradigm
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

db: test_zw
debugs: ["4个pk，共5条数据"]
version: 0.5.0
cases:
  -
    id: 0
    desc: 3个pk，每个pk5条
    inputs:
      -
        columns: ["id int","c1 string","c3 int","c4 bigint","c5 float","c6 double","c7 timestamp","c8 date"]
        indexs: ["index1:c1:c7"]
        rows:
          - [1,"aa",20,30,1.1,2.1,1000,"2020-05-01"]
          - [2,"aa",21,31,1.2,2.2,2000,"2020-05-02"]
          - [3,"aa",22,32,1.3,2.3,3000,"2020-05-03"]
          - [4,"aa",23,33,1.4,2.4,4000,"2020-05-04"]
          - [5,"aa",24,34,1.5,2.5,5000,"2020-05-05"]
          - [6,"bb",20,30,1.1,2.1,1000,"2020-05-01"]
          - [7,"bb",21,31,1.2,2.2,2000,"2020-05-02"]
          - [8,"bb",22,32,1.3,2.3,3000,"2020-05-03"]
          - [9,"bb",23,33,1.4,2.4,4000,"2020-05-04"]
          - [10,"bb",24,34,1.5,2.5,5000,"2020-05-05"]
          - [11,"cc",20,30,1.1,2.1,1000,"2020-05-01"]
          - [12,"cc",21,31,1.2,2.2,2000,"2020-05-02"]
          - [13,"cc",22,32,1.3,2.3,3000,"2020-05-03"]
          - [14,"cc",23,33,1.4,2.4,4000,"2020-05-04"]
          - [15,"cc",24,34,1.5,2.5,5000,"2020-05-05"]
    sql: |
      SELECT id, c1, sum(c4) OVER w1 as w1_c4_sum FROM {0} WINDOW w1 AS (PARTITION BY {0}.c1 ORDER BY {0}.c7 d[0]);
    dataProvider:
      - ["ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW","ROWS_RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW"]
    expectProvider:
      0:
        order: id
        columns: ["id int","c1 string","w1_c4_sum bigint"]
        rows:
          - [1,"aa",30]
          - [2,"aa",61]
          - [3,"aa",93]
          - [4,"aa",126]
          - [5,"aa",160]
          - [6,"bb",30]
          - [7,"bb",61]
          - [8,"bb",93]
          - [9,"bb",126]
          - [10,"bb",160]
          - [11,"cc",30]
          - [12,"cc",61]
          - [13,"cc",93]
          - [14,"cc",126]
          - [15,"cc",160]
      1:
        order: id
        columns: ["id int","c1 string","w1_c4_sum bigint"]
        rows:
          - [1,"aa",30]
          - [2,"aa",61]
          - [3,"aa",93]
          - [4,"aa",126]
          - [5,"aa",160]
          - [6,"bb",30]
          - [7,"bb",61]
          - [8,"bb",93]
          - [9,"bb",126]
          - [10,"bb",160]
          - [11,"cc",30]
          - [12,"cc",61]
          - [13,"cc",93]
          - [14,"cc",126]
          - [15,"cc",160]
  -
    id: 1
    desc: 3个pk，每个pk6条
    inputs:
      -
        columns: ["id int","c1 string","c3 int","c4 bigint","c5 float","c6 double","c7 timestamp","c8 date"]
        indexs: ["index1:c1:c7"]
        rows:
          - [1,"aa",20,30,1.1,2.1,1000,"2020-05-01"]
          - [2,"aa",21,31,1.2,2.2,2000,"2020-05-02"]
          - [3,"aa",22,32,1.3,2.3,3000,"2020-05-03"]
          - [4,"aa",23,33,1.4,2.4,4000,"2020-05-04"]
          - [5,"aa",24,34,1.5,2.5,5000,"2020-05-05"]
          - [6,"bb",20,30,1.1,2.1,1000,"2020-05-01"]
          - [7,"bb",21,31,1.2,2.2,2000,"2020-05-02"]
          - [8,"bb",22,32,1.3,2.3,3000,"2020-05-03"]
          - [9,"bb",23,33,1.4,2.4,4000,"2020-05-04"]
          - [10,"bb",24,34,1.5,2.5,5000,"2020-05-05"]
          - [11,"cc",20,30,1.1,2.1,1000,"2020-05-01"]
          - [12,"cc",21,31,1.2,2.2,2000,"2020-05-02"]
          - [13,"cc",22,32,1.3,2.3,3000,"2020-05-03"]
          - [14,"cc",23,33,1.4,2.4,4000,"2020-05-04"]
          - [15,"cc",24,34,1.5,2.5,5000,"2020-05-05"]
          - [16,"aa",24,35,1.5,2.5,6000,"2020-05-05"]
          - [17,"bb",24,35,1.5,2.5,6000,"2020-05-05"]
          - [18,"cc",24,35,1.5,2.5,6000,"2020-05-05"]
    sql: |
      SELECT id, c1, sum(c4) OVER w1 as w1_c4_sum FROM {0} WINDOW w1 AS (PARTITION BY {0}.c1 ORDER BY {0}.c7 d[0]);
    dataProvider:
      - ["ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW","ROWS_RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW"]
    expectProvider:
      0:
        order: id
        columns: ["id int","c1 string","w1_c4_sum bigint"]
        rows:
          - [1,"aa",30]
          - [2,"aa",61]
          - [3,"aa",93]
          - [4,"aa",126]
          - [5,"aa",160]
          - [6,"bb",30]
          - [7,"bb",61]
          - [8,"bb",93]
          - [9,"bb",126]
          - [10,"bb",160]
          - [11,"cc",30]
          - [12,"cc",61]
          - [13,"cc",93]
          - [14,"cc",126]
          - [15,"cc",160]
          - [16,"aa",195]
          - [17,"bb",195]
          - [18,"cc",195]
      1:
        order: id
        columns: ["id int","c1 string","w1_c4_sum bigint"]
        rows:
          - [1,"aa",30]
          - [2,"aa",61]
          - [3,"aa",93]
          - [4,"aa",126]
          - [5,"aa",160]
          - [6,"bb",30]
          - [7,"bb",61]
          - [8,"bb",93]
          - [9,"bb",126]
          - [10,"bb",160]
          - [11,"cc",30]
          - [12,"cc",61]
          - [13,"cc",93]
          - [14,"cc",126]
          - [15,"cc",160]
          - [16,"aa",195]
          - [17,"bb",195]
          - [18,"cc",195]
  -
    id: 2
    desc: 4个pk，每个pk1条
    inputs:
      -
        columns : ["id int","c1 string","c3 int","c4 bigint","c5 float","c6 double","c7 timestamp","c8 date"]
        indexs: ["index1:c1:c7"]
        rows:
          - [1,"aa",20,30,1.1,2.1,1590738990000,"2020-05-01"]
          - [2,"bb",21,31,1.2,2.2,1590738990001,"2020-05-02"]
          - [3,"cc",22,32,1.3,2.3,1590738990002,"2020-05-03"]
          - [4,"dd",23,33,1.4,2.4,1590738990003,"2020-05-04"]
    dataProvider:
      - ["ROWS","ROWS_RANGE"]
    sql: |
      SELECT id, c1, sum(c4) OVER w1 as w1_c4_sum FROM {0} WINDOW w1 AS (PARTITION BY {0}.c1 ORDER BY {0}.c7 d[0] BETWEEN 6 PRECEDING AND CURRENT ROW);
    expect:
      order: id
      columns: ["id int","c1 string","w1_c4_sum bigint"]
      rows:
        - [1,"aa",30]
        - [2,"bb",31]
        - [3,"cc",32]
        - [4,"dd",33]
  -
    id: 3
    desc: 4个pk，共5条数据
    inputs:
      -
        columns : ["id int","c1 string","c3 int","c4 bigint","c5 float","c6 double","c7 timestamp","c8 date"]
        indexs: ["index1:c1:c7"]
        rows:
          - [1,"aa",20,30,1.1,2.1,1590738990000,"2020-05-01"]
          - [2,"bb",21,31,1.2,2.2,1590738990001,"2020-05-02"]
          - [3,"cc",22,32,1.3,2.3,1590738990002,"2020-05-03"]
          - [4,"dd",23,33,1.4,2.4,1590738990003,"2020-05-04"]
          - [5,"dd",23,33,1.4,2.4,1590738990004,"2020-05-04"]
    sql: select c1,count(c1) as c1_count from {0} group by c1;
    expect:
      order: c1
      columns: ["c1 string","c1_count bigint"]
      rows:
        - ["aa",1]
        - ["bb",1]
        - ["cc",1]
        - ["dd",2]
  -
    id: 4
    desc: 1个pk，共6条数据
    inputs:
      -
        columns : ["id int","c1 string","c3 int","c4 bigint","c5 float","c6 double","c7 timestamp","c8 date"]
        indexs: ["index1:c1:c7"]
        rows:
          - [1,"aa",20,30,1.1,2.1,1590738990000,"2020-05-01"]
          - [2,"aa",21,31,1.2,2.2,1590738990001,"2020-05-02"]
          - [3,"aa",22,32,1.3,2.3,1590738990002,"2020-05-03"]
          - [4,"aa",23,33,1.4,2.4,1590738990003,"2020-05-04"]
          - [5,"aa",23,33,1.4,2.4,1590738990004,"2020-05-04"]
          - [6,"aa",23,33,1.4,2.4,1590738990005,"2020-05-04"]
    sql: select count(*) total_count from {0};
    expect:
      columns: ["total_count bigint"]
      rows:
        - [6]
  -
    id: 5
    desc: 4个pk，共5条数据
    inputs:
      -
        columns : ["id int","c1 string","c3 int","c4 bigint","c5 float","c6 double","c7 timestamp","c8 date"]
        indexs: ["index1:c1:c7"]
        rows:
          - [1,"aa",20,30,1.1,2.1,1590738990000,"2020-05-01"]
          - [2,"bb",21,31,1.2,2.2,1590738990001,"2020-05-02"]
          - [3,"cc",22,32,1.3,2.3,1590738990002,"2020-05-03"]
          - [4,"dd",23,33,1.4,2.4,1590738990003,"2020-05-04"]
          - [5,"dd",23,33,1.4,2.4,1590738990004,"2020-05-04"]
    sql: select count(c1) as c1_count from {0};
    expect:
      order: c1
      columns: ["c1_count bigint"]
      rows:
        - [5]
  -
    id: 6
    desc: 4个pk，共5条数据
    inputs:
      -
        columns : ["id int","c1 string","c3 int","c4 bigint","c5 float","c6 double","c7 timestamp","c8 date"]
        indexs: ["index1:c1:c7"]
        rows:
          - [1,"aa",20,30,1.1,2.1,1590738990000,"2020-05-01"]
          - [2,"bb",21,31,1.2,2.2,1590738990001,"2020-05-02"]
          - [3,"cc",22,32,1.3,2.3,1590738990002,"2020-05-03"]
          - [4,"dd",23,33,1.4,2.4,1590738990003,"2020-05-04"]
          - [5,"dd",23,33,1.4,2.4,1590738990004,"2020-05-04"]
    sql: select c3,count(c1) as c1_count from {0} group by c3;
    expect:
      order: c3
      columns: ["c3 string","c1_count bigint"]
      rows:
        - [20,1]
        - [21,1]
        - [22,1]
        - [23,2]