{
 "title": "rtidb databoard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "tablet-log",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rtidb_log{role=\"tablet\",type=\"reconnect_num\"}\t",
     "legendFormat": "{{type}} - {{instance}}"
    },
    {
     "expr": "rtidb_log{role=\"tablet\",type=\"restart_num\"}\t",
     "legendFormat": "{{type}} - {{instance}}"
    }
   ]
  },
  {
   "title": "ns-log",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rtidb_log{role=\"ns\",type=\"reconnect_num\"}\t",
     "legendFormat": "{{type}} - {{instance}}"
    },
    {
     "expr": "rtidb_log{role=\"ns\",type=\"restart_num\"}\t",
     "legendFormat": "{{type}} - {{instance}}"
    }
   ]
  },
  {
   "title": "subquery-latency",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "rtidb_subquery{latency=\"latency\",type=\"latency_50\"}",
     "legendFormat": "{{type}}-{{instance}}"
    },
    {
     "expr": "rtidb_subquery{latency=\"latency\",type=\"latency_90\"}",
     "legendFormat": "{{type}}-{{instance}}"
    },
    {
     "expr": "rtidb_subquery{latency=\"latency\",type=\"latency_99\"}",
     "legendFormat": "{{type}}-{{instance}}"
    },
    {
     "expr": "rtidb_subquery{latency=\"latency\",type=\"latency_999\"}",
     "legendFormat": "{{type}}-{{instance}}"
    },
    {
     "expr": "rtidb_subquery{latency=\"latency\",type=\"latency_9999\"}",
     "legendFormat": "{{type}}-{{instance}}"
    },
    {
     "expr": "rtidb_subquery{latency=\"latency\",type=\"max_latency\"}",
     "legendFormat": "{{type}}-{{instance}}"
    },
    {
     "expr": "rtidb_subquery{latency=\"latency\",type=\"latency\"}",
     "legendFormat": "{{type}}-{{instance}}"
    }
   ]
  },
  {
   "title": "batchquery-latency",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "rtidb_batchquery{latency=\"latency\",type=\"latency_50\"}",
     "legendFormat": "{{type}}-{{instance}}"
    },
    {
     "expr": "rtidb_batchquery{latency=\"latency\",type=\"latency_90\"}",
     "legendFormat": "{{type}}-{{instance}}"
    },
    {
     "expr": "rtidb_batchquery{latency=\"latency\",type=\"latency_99\"}",
     "legendFormat": "{{type}}-{{instance}}"
    },
    {
     "expr": "rtidb_batchquery{latency=\"latency\",type=\"latency_999\"}",
     "legendFormat": "{{type}}-{{instance}}"
    },
    {
     "expr": "rtidb_batchquery{latency=\"latency\",type=\"latency_9999\"}",
     "legendFormat": "{{type}}-{{instance}}"
    },
    {
     "expr": "rtidb_batchquery{latency=\"latency\",type=\"max_latency\"}",
     "legendFormat": "{{type}}-{{instance}}"
    },
    {
     "expr": "rtidb_batchquery{latency=\"latency\",type=\"latency\"}",
     "legendFormat": "{{type}}-{{instance}}"
    }
   ]
  },
  {
   "title": "scan-latency",
   "type": "graph",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "rtidb_scan{latency=\"latency\",type=\"latency_50\"}",
     "legendFormat": "{{type}}-{{instance}}"
    },
    {
     "expr": "rtidb_scan{latency=\"latency\",type=\"latency_90\"}",
     "legendFormat": "{{type}}-{{instance}}"
    },
    {
     "expr": "rtidb_scan{latency=\"latency\",type=\"latency_99\"}",
     "legendFormat": "{{type}}-{{instance}}"
    },
    {
     "expr": "rtidb_scan{latency=\"latency\",type=\"latency_999\"}",
     "legendFormat": "{{type}}-{{instance}}"
    },
    {
     "expr": "rtidb_scan{latency=\"latency\",type=\"latency_9999\"}",
     "legendFormat": "{{type}}-{{instance}}"
    },
    {
     "expr": "rtidb_scan{latency=\"latency\",type=\"max_latency\"}",
     "legendFormat": "{{type}}-{{instance}}"
    },
    {
     "expr": "rtidb_scan{latency=\"latency\",type=\"latency\"}",
     "legendFormat": "{{type}}-{{instance}}"
    }
   ]
  },
  {
   "title": "put-latency",
   "type": "graph",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "rtidb_put{latency=\"latency\",type=\"latency_50\"}",
     "legendFormat": "{{type}}-{{instance}}"
    },
    {
     "expr": "rtidb_put{latency=\"latency\",type=\"latency_90\"}",
     "legendFormat": "{{type}}-{{instance}}"
    },
    {
     "expr": "rtidb_put{latency=\"latency\",type=\"latency_99\"}",
     "legendFormat": "{{type}}-{{instance}}"
    },
    {
     "expr": "rtidb_put{latency=\"latency\",type=\"latency_999\"}",
     "legendFormat": "{{type}}-{{instance}}"
    },
    {
     "expr": "rtidb_put{latency=\"latency\",type=\"latency_9999\"}",
     "legendFormat": "{{type}}-{{instance}}"
    },
    {
     "expr": "rtidb_put{latency=\"latency\",type=\"max_latency\"}",
     "legendFormat": "{{type}}-{{instance}}"
    },
    {
     "expr": "rtidb_put{latency=\"latency\",type=\"latency\"}",
     "legendFormat": "{{type}}-{{instance}}"
    }
   ]
  },
  {
   "title": "query-latency",
   "type": "graph",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "rtidb_query{latency=\"latency\",type=\"latency_50\"}",
     "legendFormat": "{{type}}-{{instance}}"
    },
    {
     "expr": "rtidb_query{latency=\"latency\",type=\"latency_90\"}",
     "legendFormat": "{{type}}-{{instance}}"
    },
    {
     "expr": "rtidb_query{latency=\"latency\",type=\"latency_99\"}",
     "legendFormat": "{{type}}-{{instance}}"
    },
    {
     "expr": "rtidb_query{latency=\"latency\",type=\"latency_999\"}",
     "legendFormat": "{{type}}-{{instance}}"
    },
    {
     "expr": "rtidb_query{latency=\"latency\",type=\"latency_9999\"}",
     "legendFormat": "{{type}}-{{instance}}"
    },
    {
     "expr": "rtidb_query{latency=\"latency\",type=\"max_latency\"}",
     "legendFormat": "{{type}}-{{instance}}"
    },
    {
     "expr": "rtidb_query{latency=\"latency\",type=\"latency\"}",
     "legendFormat": "{{type}}-{{instance}}"
    }
   ]
  },
  {
   "title": "get-latency",
   "type": "graph",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "rtidb_get{latency=\"latency\",type=\"latency_50\"}",
     "legendFormat": "{{type}}-{{instance}}"
    },
    {
     "expr": "rtidb_get{latency=\"latency\",type=\"latency_90\"}",
     "legendFormat": "{{type}}-{{instance}}"
    },
    {
     "expr": "rtidb_get{latency=\"latency\",type=\"latency_99\"}",
     "legendFormat": "{{type}}-{{instance}}"
    },
    {
     "expr": "rtidb_get{latency=\"latency\",type=\"latency_999\"}",
     "legendFormat": "{{type}}-{{instance}}"
    },
    {
     "expr": "rtidb_get{latency=\"latency\",type=\"latency_9999\"}",
     "legendFormat": "{{type}}-{{instance}}"
    },
    {
     "expr": "rtidb_get{latency=\"latency\",type=\"max_latency\"}",
     "legendFormat": "{{type}}-{{instance}}"
    },
    {
     "expr": "rtidb_get{latency=\"latency\",type=\"latency\"}",
     "legendFormat": "{{type}}-{{instance}}"
    }
   ]
  },
  {
   "title": "sqlbatchrequestquery-latency",
   "type": "graph",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "rtidb_sqlbatchrequestquery{latency=\"latency\",type=\"latency_50\"}",
     "legendFormat": "{{type}}-{{instance}}"
    },
    {
     "expr": "rtidb_sqlbatchrequestquery{latency=\"latency\",type=\"latency_90\"}",
     "legendFormat": "{{type}}-{{instance}}"
    },
    {
     "expr": "rtidb_sqlbatchrequestquery{latency=\"latency\",type=\"latency_99\"}",
     "legendFormat": "{{type}}-{{instance}}"
    },
    {
     "expr": "rtidb_sqlbatchrequestquery{latency=\"latency\",type=\"latency_999\"}",
     "legendFormat": "{{type}}-{{instance}}"
    },
    {
     "expr": "rtidb_sqlbatchrequestquery{latency=\"latency\",type=\"latency_9999\"}",
     "legendFormat": "{{type}}-{{instance}}"
    },
    {
     "expr": "rtidb_sqlbatchrequestquery{latency=\"latency\",type=\"max_latency\"}",
     "legendFormat": "{{type}}-{{instance}}"
    },
    {
     "expr": "rtidb_sqlbatchrequestquery{latency=\"latency\",type=\"latency\"}",
     "legendFormat": "{{type}}-{{instance}}"
    }
   ]
  },
  {
   "title": "subbatchrequestquery-latency",
   "type": "graph",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "rtidb_subbatchrequestquery{latency=\"latency\",type=\"latency_50\"}",
     "legendFormat": "{{type}}-{{instance}}"
    },
    {
     "expr": "rtidb_subbatchrequestquery{latency=\"latency\",type=\"latency_90\"}",
     "legendFormat": "{{type}}-{{instance}}"
    },
    {
     "expr": "rtidb_subbatchrequestquery{latency=\"latency\",type=\"latency_99\"}",
     "legendFormat": "{{type}}-{{instance}}"
    },
    {
     "expr": "rtidb_subbatchrequestquery{latency=\"latency\",type=\"latency_999\"}",
     "legendFormat": "{{type}}-{{instance}}"
    },
    {
     "expr": "rtidb_subbatchrequestquery{latency=\"latency\",type=\"latency_9999\"}",
     "legendFormat": "{{type}}-{{instance}}"
    },
    {
     "expr": "rtidb_subbatchrequestquery{latency=\"latency\",type=\"max_latency\"}",
     "legendFormat": "{{type}}-{{instance}}"
    },
    {
     "expr": "rtidb_subbatchrequestquery{latency=\"latency\",type=\"latency\"}",
     "legendFormat": "{{type}}-{{instance}}"
    }
   ]
  },
  {
   "title": "qps",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rtidb_get{latency=\"type\",type=\"qps\"}",
     "legendFormat": "get-{{type}}-{{instance}}"
    },
    {
     "expr": "rtidb_put{latency=\"type\",type=\"qps\"}",
     "legendFormat": "put-{{type}}-{{instance}}"
    },
    {
     "expr": "rtidb_scan{latency=\"type\",type=\"qps\"}",
     "legendFormat": "scan-{{type}}-{{instance}}"
    },
    {
     "expr": "rtidb_batchquery{latency=\"type\",type=\"qps\"}",
     "legendFormat": "batchquery-{{type}}-{{instance}}"
    },
    {
     "expr": "rtidb_query{latency=\"type\",type=\"qps\"}",
     "legendFormat": "query-{{type}}-{{instance}}"
    },
    {
     "expr": "rtidb_sqlbatchrequestquery{latency=\"type\",type=\"qps\"}",
     "legendFormat": "sqlbatchrequestquery-{{type}}-{{instance}}"
    },
    {
     "expr": "rtidb_subquery{latency=\"type\",type=\"qps\"}",
     "legendFormat": "sub-query-{{type}}-{{instance}}"
    }
   ]
  },
  {
   "title": "count",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 62 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rtidb_get{latency=\"type\",type=\"count\"}",
     "legendFormat": "get-{{type}}-{{instance}}"
    },
    {
     "expr": "rtidb_put{latency=\"type\",type=\"count\"}",
     "legendFormat": "put-{{type}}-{{instance}}"
    },
    {
     "expr": "rtidb_scan{latency=\"type\",type=\"count\"}",
     "legendFormat": "scan-{{type}}-{{instance}}"
    },
    {
     "expr": "rtidb_batchquery{latency=\"type\",type=\"count\"}",
     "legendFormat": "batchquery-{{type}}-{{instance}}"
    },
    {
     "expr": "rtidb_query{latency=\"type\",type=\"count\"}",
     "legendFormat": "query-{{type}}-{{instance}}"
    },
    {
     "expr": "rtidb_sqlbatchrequestquery{latency=\"type\",type=\"count\"}",
     "legendFormat": "sqlbatchrequestquery-{{type}}-{{instance}}"
    },
    {
     "expr": "rtidb_subquery{latency=\"type\",type=\"count\"}",
     "legendFormat": "sub-query-{{type}}-{{instance}}"
    }
   ]
  },
  {
   "title": "rtidb memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 75 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "rtidb_memory", "legendFormat": "{{instance}}-{{type}}" }
   ]
  }
 ]
}