[tool.poetry]
name = "openmldb-exporter"
version = "0.1.0"
description = "prometheus exporter for OpenMLDB"
authors = ["aceforeverd <teapot@aceforeverd.com>"]
license = "Apache-2.0"

[tool.poetry.scripts]
openmldb_exporter = "openmldb_exporter:main"

[tool.poetry.dependencies]
python = "^3.8"
prometheus-client = "^0.12.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
