#!/bin/bash

set -eE

PATCH_FILE=$1

if [ ! -r "$PATCH_FILE" ]; then
    echo "$PATCH_FILE not available"
    exit 1
fi

sed -i"" -e "1s/^/<!--\nGenerated by 'make udf_doc_gen'.  DO NOT EDIT!\n/" "$PATCH_FILE"

sed -i"" -e "s/## Functions Documentation/## Functions Documentation\n-->\n## Built-in Functions\n/g" "$PATCH_FILE"
