[tool.poetry]
name = "udf_doxygen"
version = "0.1.0"
description = "generate udf documents for OpenMLDB"
authors = ["aceforeverd <teapot@aceforeverd.com>"]
license = "Apache-2.0"

[tool.poetry.dependencies]
python = "^3.8"
PyYAML = "^6.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
