name: "embedding"
backend: "oneflow"
max_batch_size: 10000

input [
  {
    name: "INPUT_0"
    data_type: TYPE_INT64
    dims: [ 41 ]
  }
]

output [
  {
    name: "OUTPUT_0"
    data_type: TYPE_FP32
    dims: [ 1 ]
  }
]

instance_group [
  {
    count: 1
    kind: KIND_GPU
    gpus: [ 0 ]
  }
]
