name: sphinx
channels:
  - conda-forge
  - defaults
dependencies:
  - alabaster=0.7.12
  - babel=2.9.1
  - brotlipy=0.7.0
  - ca-certificates=2022.3.29
  - certifi=2021.10.8
  - cffi=1.15.0
  - charset-normalizer=2.0.4
  - colorama=0.4.4
  - cryptography=36.0.0
  - docutils=0.17.1
  - idna=3.3
  - imagesize=1.3.0
  - importlib-metadata=4.11.3
  - jinja2=3.0.3
  - markupsafe=2.0.1
  - openssl=1.1.1n
  - packaging=21.3
  - pip=21.2.4
  - pycparser=2.21
  - pygments=2.11.2
  - pyopenssl=22.0.0
  - pyparsing=3.0.4
  - pysocks=1.7.1
  - python=3.9.12
  - pytz=2021.3
  - requests=2.27.1
  - setuptools=58.0.4
  - snowballstemmer=2.2.0
  - sphinx=4.5.0
  - sphinxcontrib-applehelp=1.0.2
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=2.0.0
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.5
  - sqlite=3.38.2
  - tk=8.6.11
  - tzdata=2022a
  - urllib3=1.26.8
  - wheel=0.37.1
  - xz=5.2.5
  - zipp=3.7.0
  - zlib=1.2.11
  - pip:
    - attrs==21.4.0
    - beautifulsoup4==4.11.1
    - linkify-it-py==1.0.3
    - markdown-it-py==2.0.1
    - mdit-py-plugins==0.3.0
    - mdurl==0.1.0
    - myst-parser==0.17.0
    - pydata-sphinx-theme==0.8.1
    - pyyaml==6.0
    - soupsieve==2.3.2
    - sphinx-book-theme==0.3.2
    - sphinx-multiversion==0.2.4
    - typing-extensions==4.1.1
    - uc-micro-py==1.0.1
    - sphinx-copybutton==0.5.0
