#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Copyright 2021 4Paradigm
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# [tool:pytest]
# addopts= --tb native -v -r fxX --maxfail=25 -p no:warnings
# python_files=/openmldb/test/*test_*.py

# [sqla_testing]
# requirement_cls=openmldb.sqlalchemy_openmldb.requirements:Requirements
# profile_file=test/profiles.txt

# [db]
# default = openmldb:///db_test?zk=127.0.0.1:6181&zkPath=/onebox
