name: auto format
on:
  schedule:
    - cron: '29 12 * * 6'
  workflow_dispatch:

jobs:
  auto-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Format
        shell: bash
        run: |
          make format
          # make sure only commit modified files
          git clean -dfx

      - name: Create PR
        uses: peter-evans/create-pull-request@v3
        with:
          title: 'style: code format changes by auto format'
          commit-message: 'auto format changes created by [create-pull-request]'
          branch: 'style/auto-format-patch'
          base: main
