name: build-and-test
on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:

env:
  GIT_SUBMODULE_STRATEGY: recursive
  HYBRIDSE_SOURCE: download

jobs:
  build_and_cpp_ut:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/4paradigm/hybridsql:0.4.0
    env:
      OS: linux
    steps:
      - uses: actions/checkout@v1
      - name: build
        run: |
          echo "build_and_cpp_ut build"
#          bash steps/init_env.sh ${{ env.HYBRIDSE_SOURCE }}
#          mkdir -p build
#          source /root/.bashrc && cd build && cmake -DSQL_PYSDK_ENABLE=OFF -DSQL_JAVASDK_ENABLE=OFF -DTESTING_ENABLE=ON .. && make -j$(nproc) && cd ../
#          rm -rf thirdparty
#      - name: run cpp
#        run: |
#          bash steps/ut.sh
#
#      - name: upload unit test results
#        if: always()
#        uses: actions/upload-artifact@v2
#        with:
#          name: linux-ut-result-cpp-${{ github.sha }}
#          path: |
#            reports/*.xml
#
#
#  publish-test-results:
#    runs-on: ubuntu-latest
#    needs: [ "build_and_cpp_ut"]
#
#    # the action will only run on 4paradigm/OpenMLDB's context, not for fork repo or dependabot
#    if: >
#      always() && github.event_name == 'push' || (
#      github.event.pull_request.head.repo.full_name == github.repository &&
#      github.event.sender.login != 'dependabot[bot]' )
#    steps:
#      - name: Download Artifacts
#        uses: actions/download-artifact@v2
#
#      - name: Publish OpenMLDB Linux UT Results
#        uses: EnricoMi/publish-unit-test-result-action@v1
#        with:
#          files: linux-ut-result-*/**/*.xml
#          check_name: Linux OpenMLDB Test Report
#          comment_title: Linux OpenMLDB Test Report
