name: DEVOPS-TEST

on:
  workflow_dispatch:
    inputs:
      PRE_UPGRADE_VERSION:
        description: 'version before upgrade'
        required: true
        default: '0.5.0'
      EXEC_TEST_TYPE:
        description: 'Which tests need to be executed? The options are all, upgrade, node_failure, node_expansion'
        required: true
        default: 'all'

env:
  GIT_SUBMODULE_STRATEGY: recursive
  HYBRIDSE_SOURCE: local

jobs:
  node-failure-test-cluster:
    if: ${{ github.event.inputs.EXEC_TEST_TYPE == 'all' || github.event.inputs.EXEC_TEST_TYPE == 'node_failure' }}
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/4paradigm/hybridsql:latest
    env:
      OS: linux
    steps:
      - uses: actions/checkout@v2
      - name: build jsdk and package
        run: |
          make configure CMAKE_INSTALL_PREFIX=openmldb-linux
          make SQL_JAVASDK_ENABLE=ON && make SQL_JAVASDK_ENABLE=ON install
          tar -zcvf openmldb-linux.tar.gz openmldb-linux
          echo "openmldb-pkg:"
          ls -al
      - name: test
        run: source /root/.bashrc && bash test/steps/openmldb-node-failure-test.sh -c test_cluster.xml -d cluster
      - name: TEST Results
        if: always()
        uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          files: test/integration-test/openmldb-test-java/openmldb-devops-test/target/surefire-reports/TEST-*.xml
          check_name: "node-failure-test-cluster Report"
          comment_title: "node-failure-test-cluster Report"

#  upgrade-test-cluster:
#    if: ${{ github.event.inputs.EXEC_TEST_TYPE == 'all' || github.event.inputs.EXEC_TEST_TYPE == 'upgrade' }}
#    runs-on: ubuntu-latest
#    container:
#      image: ghcr.io/4paradigm/hybridsql:latest
#    env:
#      OS: linux
#    steps:
#      - uses: actions/checkout@v2
#      - name: modify-properties
#        run: sh test/steps/modify-properties.sh ${{ github.event.inputs.JAVA_SDK_VERSION }} ${{ github.event.inputs.OPENMLDB_SERVER_VERSION }} ${{ github.event.inputs.PYTHON_SDK_VERSION }} ${{ github.event.inputs.BATCH_VERSION }} ${{ github.event.inputs.DIFF_VERSIONS }}
#      - name: test
#        run: source /root/.bashrc && bash test/steps/openmldb-sdk-test-java.sh -b PKG -c test_all.xml -d cluster -l "0"
#      - name: TEST Results
#        if: always()
#        uses: EnricoMi/publish-unit-test-result-action@v1
#        with:
#          files: test/integration-test/openmldb-test-java/openmldb-sdk-test/target/surefire-reports/TEST-*.xml
#          comment_mode: "create new"
#          check_name: Java SDK Test Cluster0 PKG Report
#          comment_title: Java SDK Test Cluster0 PKG Report



