name: publish-test-result-from-fork

on:
  # the action will only run on dependabot/fork pull request
  workflow_run:
    workflows: ["SDK"]
    types:
      - completed

jobs:
  test-results:
    uses: ./.github/workflows/publish-test-result-from-fork-template.yml
    with:
      name: Publish SDK UT Results
      check_name: SDK Test Report
      comment_title: SDK Test Report