on:
  workflow_call:
    inputs:
      files:
        required: true
        type: string
      check_name:
        required: true
        type: string
      comment_title:
        required: true
        type: string

permissions:
  checks: write
  pull-requests: write

jobs:
  publish-test-results:
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3

      - name: Publish Linux UT Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: ${{ inputs.files }}
          check_name: ${{ inputs.check_name }}
          comment_title: ${{ inputs.comment_title }}
