on:
  workflow_call:
    inputs:
      commit:
        required: true
        type: string
      files:
        required: true
        type: string
      check_name:
        required: true
        type: string
      comment_title:
        required: true
        type: string

jobs:
  test-results:
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/github-script@v3
        with:
          script: |
            var fs = require('fs');
            var path = require('path');
            var artifacts_path = path.join('${{github.workspace}}', 'artifacts')
            fs.mkdirSync(artifacts_path, { recursive: true })

            var artifacts = await github.actions.listWorkflowRunArtifacts({
               owner: context.repo.owner,
               repo: context.repo.repo,
               run_id: ${{ github.event.workflow_run.id }},
            });

            for (const artifact of artifacts.data.artifacts) {
               var download = await github.actions.downloadArtifact({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  artifact_id: artifact.id,
                  archive_format: 'zip',
               });
               var artifact_path = path.join(artifacts_path, `${artifact.name}.zip`)
               fs.writeFileSync(artifact_path, Buffer.from(download.data));
               console.log(`Downloaded ${artifact_path}`);
            }
      - name: Extract Artifacts
        run: |
          for file in artifacts/*.zip
          do
            if [ -f "$file" ]
            then
              dir="${file/%.zip/}"
              mkdir -p "$dir"
              unzip -d "$dir" "$file"
            fi
          done
      - name: Publish UT Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          commit: ${{ inputs.commit }}
          files: ${{ inputs.files }}
          check_name: ${{ inputs.check_name }}
          comment_title: ${{ inputs.comment_title }}
