on:
  workflow_call:
    inputs:
      commit:
        required: true
        type: string
      files:
        required: true
        type: string
      event_name:
        required: true
        type: string
      check_name:
        required: true
        type: string
      comment_title:
        required: true
        type: string
      run_id:
        required: true
        type: number

permissions:
  checks: write
  pull-requests: write

  # required by download step to access artifacts API
  actions: read

jobs:
  test-results:
    runs-on: ubuntu-latest
    steps:
      - name: Download and Extract Artifacts
        uses: dawidd6/action-download-artifact@v6
        with:
            run_id: ${{ inputs.run_id }}
            path: artifacts

      - name: Publish UT Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          commit: ${{ inputs.commit }}
          files: ${{ inputs.files }}
          check_name: ${{ inputs.check_name }}
          comment_title: ${{ inputs.comment_title }}
          event_name: ${{ inputs.event_name }}
          # u should upload the event file with upload name 'event-file'
          event_file: artifacts/event-file/event.json
