name: release
on:
  push:
    branches:
      - main  
      - feat/package
    tags:
      - 'v*'
  pull_request:

env:
  GIT_SUBMODULE_STRATEGY: recursive
jobs:
  build:
    runs-on: self-hosted
    container:
      image: ghcr.io/4paradigm/centos6_gcc7_hybridsql:latest 
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.CR_PAT_ZW }}
    steps:
      - uses: actions/checkout@v1
      - name: update submodule
        run: |
           /opt/rh/sclo-git212/root/usr/bin/git submodule update --init
      - name: uncompress_thirdparty
        run: cd /depends && tar -zxf thirdparty.tar.gz 
      - name: get version and set github env
        run: |
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          [ "$VERSION" == "main" ] && VERSION=latest
          [ "$VERSION" == "package" ] && VERSION=beta
          FILE_NAME=fedb-cluster-$VERSION.tar.gz
          echo VERSION=$VERSION
          echo FILE_NAME=$FILE_NAME
          echo "RELEASE_VERSION=$VERSION" >> $GITHUB_ENV
          echo "FILE_NAME=$FILE_NAME" >> $GITHUB_ENV
          bash steps/release.sh $VERSION
      - name: build_fesql
        run: bash tools/install_hybridse.sh
      - name: build_fedb
        run: |
          ln -sf /depends/thirdparty thirdparty
          ln -sf /depends/thirdsrc thirdsrc
          bash steps/simple_compile.sh
      - name: package fedb
        run: |
          source /root/.bashrc && bash steps/package_fedb.sh ${{ env.RELEASE_VERSION }}
      - uses: meeDamian/github-release@2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ env.RELEASE_VERSION }}
          name: ${{ env.FILE_NAME }}
          gzip: false
          files: ${{ env.FILE_NAME }} 
          allow_override: true

      #- name: package java sdk
      #  run: |
      #    source /root/.bashrc && bash steps/package_fedb_javasdk.sh

      - name: cleanup
        if: always()
        run: |
          source /etc/profile.d/enable-rh.sh
          git clean -dfx
          test -d fesql && cd fesql && git clean -dfx
