name: sql_cluster_test
on: [pull_request]
env:
  GIT_SUBMODULE_STRATEGY: recursive

jobs:
  sql_cluster_test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/4paradigm/hybridsql:0.2.0
    steps:
      - uses: actions/checkout@v1
      - name: uncompress_thirdparty
        run: |
          cd /depends && tar -zxf thirdparty.tar.gz && cd -
      - name: build
        run: |
          bash steps/init_env.sh
          mkdir -p build
          source /root/.bashrc && cd build && cmake -DSQL_PYSDK_ENABLE=OFF -DSQL_JAVASDK_ENABLE=OFF -DTESTING_ENABLE=ON .. && make -j$(nproc) sql_cluster_test && cd ../
      - name: run sql_sdk_test
        run: |
          bash steps/ut.sh sql_cluster_test 0
      - name: upload unit test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: linux-ut-result-cpp-cluster-${{ github.sha }}
          path: |
            reports/*.xml
      - name: cleanup
        if: always()
        run: |
          source /etc/profile.d/enable-rh.sh
          git clean -dfx  